input {
    gelf {
        host => "0.0.0.0"  # Listen on all interfaces
        port => 5000       # Port to receive GELF logs
    }
}

filter {
    if [service] == "jenkins" {
        grok {
            match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
        }
        date {
            match => ["timestamp", "ISO8601"]
        }
    } else if [service] == "app-tpfoyer" {
        grok {
            match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
        }
        date {
            match => ["timestamp", "ISO8601"]
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://192.168.33.10:9200"]  # Adjust if needed
        index => "devops-logs-%{+YYYY.MM.dd}"      # Index name for Elasticsearch
    }
}
